<br /><br />
<div style="width:300px;font-family:Arial,Helvetica,sans-serif;font-size:10px;background-color:#ffffff;color:#000">

 <div style="height:25px;text-align:center">
  <img src="http://payment.allopass.com/imgweb/script/fr_uk/acces_title.jpg" width="300" height="25" alt="Logo" />
 </div>

 <div style="height:137px;text-align:center">
  <img name="acces_top" src="http://payment.allopass.com/acte/scripts/popup/top.apu?ids={ids}&amp;idd={idd}&amp;lang=fr" width="300" height="137" alt="" />
 </div>

 <div style="width:300px;text-align:right">
  <img src="http://payment.allopass.com/imgweb/script/fr_uk/acces_left.jpg" width="79" height="29" alt="" style="float:left" />
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=fr','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_fr.gif" width="35" height="29" alt="FR" title="FR" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=be','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_be.gif" width="35" height="29" alt="BE" title="BE" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=ch','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_ch.gif" width="35" height="29" alt="CH" title="CH" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=lu','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_lu.gif" width="35" height="29" alt="LU" title="LU" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=de','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_de.gif" width="35" height="29" alt="DE" title="DE" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=uk','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_uk.gif" width="35" height="29" alt="UK" title="UK" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=nl','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_nl.gif" width="35" height="29" alt="NL" title="NL" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=es','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_es.gif" width="35" height="29" alt="ES" title="ES" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=at','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_at.gif" width="35" height="29" alt="AT" title="AT" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=it','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_it.gif" width="35" height="29" alt="IT" title="IT" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=pt','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_pt.gif" width="35" height="29" alt="PT" title="PT" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=se','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_se.gif" width="35" height="29" alt="SE" title="SE" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=no','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_no.gif" width="35" height="29" alt="NO" title="NO" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=fi','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_fi.gif" width="35" height="29" alt="FI" title="FI" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=gr','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_gr.gif" width="35" height="29" alt="GR" title="GR" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=cz','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_cz.gif" width="35" height="29" alt="CZ" title="CZ" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=pl','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_pl.gif" width="35" height="29" alt="PL" title="PL" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=lt','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_lt.gif" width="35" height="29" alt="LT" title="LT" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=ee','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_ee.gif" width="35" height="29" alt="EE" title="EE" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=ro','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_ro.gif" width="35" height="29" alt="RO" title="RO" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=lv','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_lv.gif" width="35" height="29" alt="LV" title="LV" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=sk','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_sk.gif" width="35" height="29" alt="SK" title="SK" /></a>
  <a href="javascript:;" onclick="javascript:window.open('http://payment.allopass.com/acte/scripts/popup/access.apu?ids={ids}&amp;idd={idd}&amp;lang=fr&amp;country=hu','phone','toolbar=0,location=0,directories=0,status=0,scrollbars=0,resizable=0,copyhistory=0,menuBar=0,width=300,height=340');"><img border="0" src="http://payment.allopass.com/imgweb/common/flag_hu.gif" width="35" height="29" alt="HU" title="HU" /></a>
 </div>

 <form name="APform" action="http://payment.allopass.com/acte/access.apu" method="post" style="text-align:center;clear:both">
<input type="hidden" name="ids" value="{ids}" />
<input type="hidden" name="idd" value="{idd}" />
<input type="hidden" name="lang" value="fr" />
<input type="hidden" name="recall" value="1" />

  <strong>Entrez votre code d'acces - <br />Enter your access code</strong><br /><br />
  <input type="text" size="8" maxlength="10" value="" name="code[]" style="background-color:#e7e7e7;border:#000080 1px solid;color:#000080;cursor:text;font-family:Arial;font-size:10pt;font-weight:bold;letter-spacing:normal;width:70px;text-align:center;" />
  <br /><br />
  <input type="button" name="APsub" value="" onclick="this.form.submit();this.form.APsub.disabled=true;" style="border:0px;margin:0px;padding:0px;width:48px;height:18px;background:url('http://payment.allopass.com/imgweb/common/bt_ok.gif');" /><br />
 </form>
 Pour connaitre notre solution de micro paiement :
 <a href="http://fr.allopass.com/" target="_blank">Allopass</a>
</div>